default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hyperlink_development

test:
  <<: *default
  database: hyperlink_test

production:
  <<: *default
  database: hyperlink_production
  username: hyperlink-project
  password: <%= ENV['HYPERLINK-PROJECT_DATABASE_PASSWORD'] %>
